# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
#
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#

# Example Variables:
#  asana:
#    accessToken: 'AIzaSyDax'
Variables:
  asana-connector:
    # The PAT key that can be created in https://app.asana.com/0/my-apps.
    accessToken: ''